Fix #56
AiursoftWeb/Kahla.Obsolete pull request #61
Opened 2019-04-11 16:32 UTC by Anduin2017

2019-04-11 16:48 UTC, ganlvtech requested changes

2019-04-11 16:48 UTC, ganlvtech commented on Kahla.Server/Services/EmailNotifier.cs
> +                        int totalUnread = 0, inConversatons = 0, pendingRequests = 0;
conversation typo

2019-04-11 16:50 UTC, ganlvtech commented
Would it send the same email twice if I didn't read any message and no any new messages received?

2019-04-11 21:49 UTC, Xiangrui2019 reviewed
good!

2019-04-12 00:51 UTC, xxyzz approved these changes
I think the user should be able to enable or disable this feature.

2019-04-12 01:55 UTC, Anduin2017 commented
@xxyzz yes we will provide notification settings

2019-04-12 03:36 UTC, ganlvtech approved these changes

2019-04-12 03:59 UTC, merged