Allow group owner to change group avatar and joinPassword
AiursoftWeb/Kahla.Obsolete pull request #70
Opened 2019-04-26 11:22 UTC by hv0905

2019-04-27 06:05 UTC, Anduin2017 commented
I will consider this later. Now Kahla isn't designed for group management. For the `ownerID` may not be accurate.

Merging this possibly means refactor some logic. And really requires our consideration.

2019-04-27 06:06 UTC, Anduin2017 commented on Kahla.Server/Controllers/GroupsController.cs
> +                return this.Protocol(ErrorType.RequireAttention, "You haven't the permission to execute this command.");
What about use errortype -8?

2019-04-27 06:07 UTC, Anduin2017 requested changes
Will considering redesign group management authorization module.

2019-04-30 04:17 UTC, Xiangrui2019 approved these changes

2019-04-30 13:11 UTC, Xiangrui2019 approved these changes

2019-04-30 18:07 UTC, ganlvtech approved these changes

2019-06-05 15:56 UTC, Anduin2017 approved these changes

2019-06-05 15:56 UTC, merged